### PR TITLE
Add OpenSSF Scorecard where available

### PR DESCRIPTION
**Pull request by ryjones**
These are the existing scorecards.

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by baentsch** [comment]
As this is now publicly available, I'd strongly suggest working on improving those scores that are published (create issues in those sub projects?).

**Comment by dstebila** [comment]
Agreed. I believe it was an action item for @planetf1 to add issues for these in the respective repositories.

**Comment by planetf1** [comment]
I opened https://github.com/open-quantum-safe/tsc/issues/27 for followup actions across other repos. Comments welcome there!

**Comment by baentsch** [comment]
> I opened [open-quantum-safe/tsc#27](https://github.com/open-quantum-safe/tsc/issues/27) for followup actions across other repos. Comments welcome there!

I do not think this was the (t)ask: I think the idea was to have single issues open (and resolve them) in each of those sub projects where you already publish scores (liboqs, liboqs-go and liboqs-rust) to clear them out before creating more bad impressions about the "security score" of further OQS sub projects.

**Pull request merged**
