### PR TITLE
Add proposed project scorecards

### PR DESCRIPTION
**Pull request by ryjones**
Per [this issue](https://github.com/open-quantum-safe/tsc/issues/27), provisionally add scorecards

### CODE REVIEW

**Comment by ryjones** [comment]
@planetf1

**Review by planetf1 — COMMENTED** [review]
@ryjones This is proactively adding the links to the badges, which will be available when the actual scorecard work is in place?

**Comment by ryjones** [comment]
Yes. For now it will show a "missing project" bug:

Screenshot 2024-05-16 at 05 22 09

**Comment by dstebila** [comment]
I would be tempted to focus the effort on resolving issues arising from the first few scorecards (and evaluating the value of that) before taking on scorecards for all the projects.

**Comment by baentsch** [comment]
Seconding the comment by @dstebila above and repeating my concerns from [the unmerged PR regarding this on liboqs](https://github.com/open-quantum-safe/liboqs/pull/1708) I consider it premature publishing results of "security score cards" before a) they have been done and b) before there's an agreed-upon plan to mitigate/resolve findings -- particularly for a project doing (at the face of it) security software.

Already for the existing score cards the question: Are there issues in github showing the path to score improvement? Are those issues assigned people to implement them? Did these people agree on a timeline when to land these improvements? If this does not exist, you'd accept publishing bad scores for an infinite time. That I'd call corrosive for a project's reputation:

If I were looking at this as a person responsible for deciding whether to use OQS or develop my own PQ software in-house, I'd surely opt for the second seeing these results.

**Comment by planetf1** [comment]
Getting liboqs clean was the first step we agreed to. Nearly there (I have some doc updates). 

https://github.com/open-quantum-safe/tsc/issues/27 can track rolling this out to more repos - I think the next target should be oqsprovider 

If there's concern about publishing the results
 * we can continue with the approach of starting on a PR to implement scorecard & add required mitigations
 * We could remove the links to the scorecard badge until a repo is 'done' with pr merged.

**Comment by baentsch** [comment]
> I think the next target should be oqsprovider

I adamantly object to that until there's more committed and achieved contributors and at least two more committed maintainers to that sub project.

**Comment by planetf1** [comment]
I mentioned oqsprovider since it's a super asset & I know it's being used. 

There's plenty to do so will work through the other items, then we'll be in a better state to review any impacts/concerns

**Pull request closed without merging**
